Allfiles: s.py r.py
	python r.py -d -p 12345 -n 400 -e 0.0000001
	python s.py -d -p 12345 -l 1500 -r 300 -n 400 -w 3 -b 10
#There is no need to generate executables for python as it is an intepreted language.
#The above commands can be used to run the programs.(receiver and sender respectively). 
