Allfiles: s1.py r.py
	python r.py -d -p 12345 -N 400 -e 0.00001 -B 100
	python s1.py -d -p 12345 -L 1500 -R 300 -N 400 -W 4 -B 100 -n 8
#There is no need to generate executables for python as it is an intepreted language.
#The above commands can be used to run the programs.(receiver and sender respectively). 
